<?php

/**
 * Created by PhpStorm.
 * User: webwerks
 * Date: 24/4/17
 * Time: 6:22 PM
 */

namespace App\Model\Table;

use Cake\Database\Schema\Table;
use Cake\Event\Event;
use Cake\Network\Session;
use Cake\ORM\Entity;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\Validation\Validator;

class UsersTable extends MasterTable {

    public function initialize(array $config) {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->table('users');
        $this->displayField('username');
        $this->primaryKey('id');
        //$this->addBehavior('timestamp');
    }

    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->isUnique('user'));
        return $rules;
    }

    public function beforeSave(Event $event, Entity $entity) {
        $session = new Session();
        if ($entity->isNew()) {
            $entity->created_by = $session->read('Auth.User.id');
            if ($entity->email_verified == '0') {
                $entity->Active = '0';
                $entity->email_verified = "0";
                $entity->email_token = md5(date('YmdHis') . $entity->email_address);
                $entity->email_token_expires = strtotime(date('Y-m-d H:i:s') . ' +1day');
            }
        } else {
            $entity->modified_by = $session->read('Auth.user.id');
        }
    }

    public function validationDefault(Validator $validator) {
        return $validator;
    }

    public function findLogin(Query $query,array $options){
        return $query->where($options)->first()->toArray();
    }

}
